### ISSUE TITLE
Code for SCG-Net Semantic Segmentation Paper

### ISSUE THREAD

**Issue by abderraouf2che** [samleoqh/MSCG-Net#27]
Hello;
Would you please upload the code for the SCG-Net Semantic Segmentation Paper, for learning and research purposes.

Thanks

**Comment by tshr-d-dragon** [comment]
Hi @abderraouf2che,

The scg_gcn.py file at https://github.com/samleoqh/MSCG-Net/blob/master/lib/net/scg_gcn.py contains the code you need.
