### ISSUE TITLE
test

### ISSUE THREAD

**Issue by zwsbh** [samleoqh/MSCG-Net#35]
How to display the test results, which is the confusion matrix

**Comment by samleoqh** [comment]
pls refer to `lib/utils/measure.py`

**Comment by zwsbh** [comment]
There is no the results of the confusion matrix when running text_submission. py

**Comment by samleoqh** [comment]
test_submission is just for the hold-out test, not for validation, there is no ground-truth for the hold-out test set, we only submit the results to the Challenge organizations, and then they will evaluate your submission on their hold-out ground-truth.

**Comment by zwsbh** [comment]
Is the indicator in the paper the result of the validation set or the test set

**Comment by zwsbh** [comment]
How to obtain the results of comparative experiments without real labels from the test set

**Comment by samleoqh** [comment]
Just compare models on your validation set. You cannot get the IOU or F1 scores on the hold-out test set now since the workshop has already ended and closed any submission evaluations.
