### ISSUE TITLE
tqdm error

### ISSUE THREAD

**Issue by mukultater** [samleoqh/MSCG-Net#5]
While running test submission.py, i am receiving this output..< 
What should i do.? Is this correct.? or there should be a progress bar here.?

"HBox(children=(FloatProgress(value=0.0, max=3729.0), HTML(value='')))
total number of sliding windows:  1"

**Comment by samleoqh** [comment]
There is an issue related to the progress bar with tqdm, but no effect for the final results. You can safely ignore it for now.

**Comment by mukultater** [comment]
Yep Its Working, 
Thanks samleoqh.

**Comment by czarmanu** [comment]
I tried with a subset of 10 images from the test set. However, I get "black" output images after running test_submission.py.

When I run: PYTHONPATH={PWD}/..:${PYTHONPATH} CUDA_VISIBLE_DEVICES=0 python3 ./tools/test_submission.py 

Following is the result in the command line:

HBox(children=(IntProgress(value=0, max=10), HTML(value='')))
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.27905702590942383
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2548341751098633
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.25104784965515137
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2509579658508301
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2509949207305908
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.25146985054016113
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2590038776397705
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2514808177947998
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2519571781158447
total number of sliding windows:  1
HBox(children=(IntProgress(value=0, max=1), HTML(value='')))
inference cost time:  0.2519662380218506

 Is it just an image-saving problem or sth else?

**Comment by czarmanu** [comment]
It was just a display error. replacing *pred* with *pred*255/7* solved the issue by displaying each class as a shade of gray.
